<?php
    /**
     * Created by PhpStorm.
     * User: Mikoto
     * Date: 11/23/2017
     * Time: 4:27 PM
     */
    
    namespace App\Extend;
    
    use Slim\Http\Response as Response;
    
    class ResponseExtend extends Response
    {
        
        
        protected $isCheckError = false;
        
        protected $errors = [];
        
        private function errorChecker()
        {
            $this->isCheckError = true;
            $this->errors = [];
            
            if (!empty($_SESSION['errors'])) {
                foreach ($_SESSION['errors'] as $item => $value) {
                    
                    $this->errors[] = [
                        "name"  => $item,
                        "title" => $value[0],
                    ];
                }
            }
            
        }
        
        public function withError()
        {
            
            if (!empty($this->errors)) {
                
                return $this->withJson();
            }
            
            return $this;
        }
        
        public function hasError()
        {
            $this->errorChecker();
            
            return !empty($this->errors);
        }
        
        
        public function withJson($data, $status = 200, $encodingOptions = 0)
        {
            if (empty($status) || $status === 200) {
                $status = 200;
            }
            
            return parent::withJson($data, $status, $encodingOptions); // TODO: Change the autogenerated stub
        }
    }